### ISSUE TITLE
Access to the dataset

### ISSUE THREAD

**Issue by kylemcdonald** [yagguc/deep_impression#1]
Hi Yağmur! Thanks for sharing this work. I was wondering if you still have access to the dataset? The links provided on CodaLab are all broken now:

* http://158.109.8.102/training/training_gt.csv
* http://158.109.8.102/download_train-val.zip
* http://158.109.8.102/download_test.zip

**Comment by kylemcdonald** [comment]
Sorry for the notice! I found the new data is available on the new site http://chalearnlap.cvc.uab.es/dataset/20/data/32/files/ (after registration)

**Comment by Serhiy-Shekhovtsov** [comment]
Many thanks for posting this!
